#1. Retrieve the total revenue generated for each film category.
select fc.category_id,sum(p.amount) as revenue
from film_category fc
join film f
on fc.film_id=f.film_id
join inventory i
on i.film_id = f.film_id
join rental r
on i.inventory_id = r.inventory_id
join payment p
on p.rental_id=r.rental_id
group by fc.category_id;

#2. Determine the count of rentals for each customer.
select r.customer_id, count(r.rental_id)
from rental r
group by r.customer_id

#3. Calculate the average rental duration (in days) for each film.
select film_id, avg(rental_duration)
from film
group by film_id

#4. Find the total revenue generated for each month.
select date_format(payment_date, '%Y-%m') as month, 
sum(amount) as total_revenue
from payment
group by date_format(payment_date, '%Y-%m')
order by month;

#5. Determine the total revenue generated by each store.
select st.store_id, sum(p.amount) as 'total amount'
from payment p
join staff s
on p.staff_id=s.staff_id
join store st
on st.store_id = s.store_id
group by st.store_id;

#6. Calculate the count of rentals handled by each staff member.
select s.staff_id,s.first_name,s.last_name,count(r.rental_id)  
from staff s
join rental r
on s.staff_id=r.staff_id
group by s.staff_id;

#7. Compute the average rental rate for each film category.
select c.category_id,f.rental_rate 
from film_category fc
join category c
on c.category_id = fc.category_id
join film f
on f.film_id = c.film_id
join rental r
on r.inventory_id=f.inventory_id
group by r.inventory_id;

#8. Determine the count of rentals for each film.
select f.title, COUNT(r.rental_id) 
as rental_count
from film f
left join rental r
on f.film_id = r.inventory_id
group by f.title;

#9. Retrieve the total revenue generated for each city.
select sum(p.amount) ,c.city_id
from city c
join address a
on c.city_id=a.city_id
join staff s
on s.address_id=a.address_id
join payment p
on p.staff_id=s.staff_id
group by c.city_id;

#10. Calculate the count of rentals for each film language.
select l.name, count(r.rental_id) 
from language l
left outer join film f on l.language_id = f.language_id
left outer join inventory i on f.film_id = i.film_id
left outer join rental r on i.inventory_id = r.inventory_id
group by l.name;